// Builds and deploys the web app, stamping a fresh build version so
// AutoReload (src/components/AutoReload.tsx) can detect it and force-reload
// any browser tab left open on an older deploy.
const fs = require("fs");
const path = require("path");
const { execSync } = require("child_process");

const root = path.join(__dirname, "..");
const version = String(Date.now());

fs.writeFileSync(
  path.join(root, "src", "buildVersion.ts"),
  `// Auto-generated by scripts/deploy-web.js on every web deploy — do not edit\n` +
    `// by hand, it gets overwritten.\n` +
    `export const BUILD_VERSION = "${version}";\n`
);

execSync("npx expo export --platform web", { stdio: "inherit", cwd: root });

const distDir = path.join(root, "dist");
fs.writeFileSync(path.join(distDir, "version.json"), JSON.stringify({ version }));

const legalDir = path.join(root, "legal");
for (const file of fs.readdirSync(legalDir)) {
  fs.copyFileSync(path.join(legalDir, file), path.join(distDir, file));
}

execSync("firebase deploy --only hosting --project ack-freight", {
  stdio: "inherit",
  cwd: root,
});
